version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_PAPERCLIP_IP
      APP_PORT: 3100

  web:
    image: ghcr.io/paperclipai/paperclip:latest
    restart: unless-stopped
    ports:
      - "${APP_PAPERCLIP_PORT}:3100"
    volumes:
      - "${APP_DATA_DIR}/data:/data"
    environment:
      - DATA_DIR=/data
